export const usersData = {
  teacher: [
    {
      id: "1",
      lable: "Teacher ID*:",
      placeholder: "",
      name: "teacher_id",
      inputType: "text",
    },
    {
      id: "2",
      lable: "First Name*:",
      placeholder: "",
      name: "first_name",
      inputType: "text",
    },
    {
      id: "3",
      lable: "Last Name*:",
      placeholder: "",
      name: "last_name",
      inputType: "text",
    },
    {
      id: "4",
      lable: "Middle initial:",
      placeholder: "",
      name: "middle_initial",
      inputType: "text",
    },
    {
      id: "5",
      lable: "Username*:",
      placeholder: "",
      name: "user_name",
      inputType: "text",
    },
    {
      id: "6",
      lable: "Email Address*:",
      placeholder: "",
      name: "email",
      inputType: "text",
    },
    {
      id: "7",
      lable: "Alternate Email Address 1:",
      placeholder: "",
      name: "email_1",
      inputType: "text",
    },
    {
      id: "8",
      lable: "Alternate Email Address 2:",
      placeholder: "",
      name: "email_2",
      inputType: "text",
    },

    {
      id: "9",
      lable: "Phone:",
      placeholder: "",
      name: "phone",
      inputType: "text",
    },
    {
      id: "10",
      lable: "Password*:",
      placeholder: "",
      name: "password",
      inputType: "text",
    },
    {
      id: "11",
      lable: "Re-enter Password*:",
      placeholder: "",
      name: "reEnterPassword",
      inputType: "text",
    },

    {
      id: "12",
      lable: "Role:",
      placeholder: "",
      name: "creater_role",
      inputType: "select",
      options: ["Teacher", "School Admin", "District Admin"],    },
    {
      groupLable: "Login Status",
      inputType: "radio",
      name:"login_status",
      group: ["Active", "Inactive"],
    },
  ],

  schoolAdmin: [
    {
      id: "1",
      lable: "School Administrator ID*:",
      placeholder: "",
      name: "schoolAdmin_id",
      inputType: "text",
    },
    {
      id: "2",
      lable: "First Name*:",
      placeholder: "",
      name: "first_name",
      inputType: "text",
    },
    {
      id: "3",
      lable: "Last Name*:",
      placeholder: "",
      name: "last_name",
      inputType: "text",
    },
    {
      id: "4",
      lable: "Middle initial:",
      placeholder: "",
      name: "middle_initial",
      inputType: "text",
    },
    {
      id: "5",
      lable: "Username*:",
      placeholder: "",
      name: "user_name",
      inputType: "text",
    },
    {
      id: "6",
      lable: "Email Address*:",
      placeholder: "",
      name: "email",
      inputType: "text",
    },
    {
      id: "7",
      lable: "Alternate Email Address 1:",
      placeholder: "",
      name: "email_1",
      inputType: "text",
    },
    {
      id: "8",
      lable: "Alternate Email Address 2:",
      placeholder: "",
      name: "email_2",
      inputType: "text",
    },

    {
      id: "9",
      lable: "Phone:",
      placeholder: "",
      name: "phone",
      inputType: "text",
    },
    {
      id: "10",
      lable: "Password*:",
      placeholder: "",
      name: "password",
      inputType: "text",
    },
    {
      id: "11",
      lable: "Re-enter Password*:",
      placeholder: "",
      name: "reEnterPassword",
      inputType: "text",
    },

    {
      id: "12",
      lable: "Role:",
      placeholder: "",
      name: "creater_role",
      inputType: "select",
      options: ["Teacher", "School Admin", "District Admin"],    },
    {
      groupLable: "Login Status",

      inputType: "radio",
      group: ["Active", "Inactive"],
    },
  ],

  districtAdmin: [
    {
      id: "1",
      lable: "District Administrator ID*:",
      placeholder: "",
      name: "district_id",
      inputType: "text",
    },
    {
      id: "2",
      lable: "First Name*:",
      placeholder: "",
      name: "first_name",
      inputType: "text",
    },
    {
      id: "3",
      lable: "Last Name*:",
      placeholder: "",
      name: "last_name",
      inputType: "text",
    },
    {
      id: "4",
      lable: "Middle initial:",
      placeholder: "",
      name: "middle_initial",
      inputType: "text",
    },
    {
      id: "5",
      lable: "Username*:",
      placeholder: "",
      name: "user_name",
      inputType: "text",
    },
    {
      id: "6",
      lable: "Email Address*:",
      placeholder: "",
      name: "email",
      inputType: "text",
    },
    {
      id: "7",
      lable: "Alternate Email Address 1:",
      placeholder: "",
      name: "email_1",
      inputType: "text",
    },
    {
      id: "8",
      lable: "Alternate Email Address 2:",
      placeholder: "",
      name: "email_2",
      inputType: "text",
    },

    {
      id: "9",
      lable: "Phone:",
      placeholder: "",
      name: "phone",
      inputType: "text",
    },
    {
      id: "10",
      lable: "Password*:",
      placeholder: "",
      name: "password",
      inputType: "text",
    },
    {
      id: "11",
      lable: "Re-enter Password*:",
      placeholder: "",
      name: "reEnterPassword",
      inputType: "text",
    },

    {
      id: "12",
      lable: "Role:",
      placeholder: "",
      name: "creater_role",
      inputType: "select",
      options: ["Teacher", "School Admin", "District Admin"],    },
    {
      groupLable: "Login Status",

      inputType: "radio",
      group: ["Active", "Inactive"],
    },
  ],

  student: [
    {
      id: "1",
      lable: "Student ID:",
      placeholder: "",
      name: "student_id",
      inputType: "text",
    },
    {
      id: "2",
      lable: "First Name*:",
      placeholder: "",
      name: "first_name",
      inputType: "text",
    },
    {
      id: "3",
      lable: "Grade*:",
      placeholder: "",
      name: "grade",
      inputType: "select",
      options: [
        "kindergarten",
        "First Grade",
        "Second Grade",
        "Third Grade",
        "Fourth Grade",
        "Fifth Grade",
        "Sixth Grade",
        "Seventh Grade",
        "Eighth Grade",
        "Ninth Grade",
        "Tenth Grade",
        "Eleventh Grade",
        "Twelth Grade",
        "Adult"
      ],
    },
    {
      id: "4",
      lable: "Student Email Address:",
      placeholder: "",
      name: "email",
      inputType: "text",
    },
    {
      id: "5",
      lable: "Username*:",
      placeholder: "",
      name: "user_name",
      inputType: "text",
    },
    {
      id: "6",
      lable: "Last Name*:",
      placeholder: "",
      name: "last_name",
      inputType: "text",
    },
    {
      id: "7",
      lable: "Birth Date*(mm/dd/yyyy)",
      placeholder: "",
      name: "date_of_birth",
      inputType: "text",
    },
    {
      id: "8",
      lable: "Parent Email Address 1:",
      placeholder: "",
      name: "parent_email_2",
      inputType: "text",
    },
    {
      id: "9",
      lable: "Password*:",
      placeholder: "",
      name: "password",
      inputType: "text",
    },

    {
      id: "10",
      lable: "Middle initial",
      placeholder: "",
      name: "middle_initial",
      inputType: "text",
    },
    {
      id: "11",
      lable: "Race:",
      placeholder: "",
      name: "race",
      inputType: "select",
      options: [
        "White",
        "Black or African American",
        "American Indian or Alaska Native",
        "Asian",
        "Native Hawailian or Other Pacific",
        "Others",
      ],
    },
    {
      id: "12",
      lable: "Parent Email Address 2:",
      placeholder: "",
      name: "parent_email_2",
      inputType: "text",
    },
    {
      id: "13",
      lable: "Re-enter-Password*:",
      placeholder: "",
      name: "password",
      inputType: "text",
    },

    {
      id: "14",
      lable: "sex Assigned At Birth*",
      placeholder: "",
      name: "gender",
      inputType: "select",
      options: ["Male", "Female"],
    },
    {
      id: "15",
      lable: "Ethnicity*",
      placeholder: "",
      name: "ethnicity",
      inputType: "select",
      options: ["Hispanic or Latino","Not Hispanic or Latino"],
    },
    {
      id: "16",
      lable: "Phone*",
      placeholder: "",
      name: "phone",
      inputType: "text",
    },

    {
      lable: "Print Body Composition",

      inputType: "checkbox",
    },
    {
      lable: "Print Reports in Spanish",

      inputType: "checkbox",
    },
    {
      lable: "Permanently Exempt",

      inputType: "checkbox",
    },
    {
      groupLable: "Login Status",

      inputType: "radio",
      group: ["Active", "Inactive"],
    },
  ],

  parent: [
    {
      id: "1",
      lable: "Parent ID*:",
      placeholder: "",
      name: "parent_id",
      inputType: "text",
    },
    {
      id: "2",
      lable: "First Name*:",
      placeholder: "",
      name: "first_name",
      inputType: "text",
    },
    {
      id: "3",
      lable: "Last Name*:",
      placeholder: "",
      name: "last_name",
      inputType: "text",
    },
    {
      id: "4",
      lable: "Middle initial:",
      placeholder: "",
      name: "middle_initial",
      inputType: "text",
    },
    {
      id: "5",
      lable: "Username*:",
      placeholder: "",
      name: "user_name",
      inputType: "text",
    },
    {
      id: "6",
      lable: "Email Address*:",
      placeholder: "",
      name: "email",
      inputType: "text",
    },
    {
      id: "7",
      lable: "Alternate Email Address 1:",
      placeholder: "",
      name: "email_1",
      inputType: "text",
    },
    {
      id: "8",
      lable: "Alternate Email Address 2:",
      placeholder: "",
      name: "email_2",
      inputType: "text",
    },

    {
      id: "9",
      lable: "Phone:",
      placeholder: "",
      name: "phone",
      inputType: "text",
    },
    {
      id: "10",
      lable: "Password*:",
      placeholder: "",
      name: "password",
      inputType: "text",
    },
    {
      id: "11",
      lable: "Re-enter Password*:",
      placeholder: "",
      name: "reEnterPassword",
      inputType: "text",
    },

    {
      id: "12",
      lable: "Role:",
      placeholder: "",
      name: "creater_role",
      inputType: "select",
      options: ["Teacher", "School Admin", "District Admin"],
    },
    {
      groupLable: "Login Status",
      inputType: "radio",
      group: ["Active", "Inactive"],
      name:'login_status'
    },
  ],

  checkBoxData: [
    {
      id: "1",
      lable: "Print Body Composition",
      placeholder: "",
    },
    {
      id: "2",
      lable: "Print Reports in Spanish",
      placeholder: "",
    },
    {
      id: "3",
      lable: "Permanently Exempt",
      placeholder: "",
    },
  ],
};
